dagster-user-deployments:
  enabled: true
  deployments:
    - name: dagster-etl
      image:
        repository: dagster-etl
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "-m"
        - "dagster_etl.definitions"
      port: 3030
      envSecrets:
        - name: s3-credentials
      nodeSelector:
        benchmark: "true"

dagsterWebserver:
  replicaCount: 1
  nodeSelector:
    benchmark: "true"

dagsterDaemon:
  nodeSelector:
    benchmark: "true"

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      runK8sConfig:
        containerConfig:
          resources:
            requests:
              cpu: "8"
              memory: "32Gi"
            limits:
              cpu: "8"
              memory: "32Gi"
        podTemplateSpecMetadata:
          nodeSelector:
            benchmark: "true"

dagster-postgresql:
  enabled: true
  postgresqlUsername: dagster
  postgresqlPassword: dagster
  postgresqlDatabase: dagster
  persistence:
    enabled: true
    size: 10Gi

computeLogManager:
  type: NoOpComputeLogManager

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 1
