name: tpcds_benchmark
version: "1.0.0"
config-version: 2

profile: tpcds_benchmark

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  tpcds_benchmark:
    +materialized: table
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
